server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tourem
    username: tourem
    password:
    maxActive: 10
    maxIdle: 5
    initialSize: 5
    removeAbandoned: true
  jpa:
    show-sql: true

logging:
  level:
    com:
      tourem: DEBUG
    root: INFO
