server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tourem
    username: tourem
    password:
  jpa:
    show-sql: true

logging:
  level:
    com:
      tourem: DEBUG
    root: INFO

cors-origin: http://localhost:4200/*
